services:
  duzz-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      # - dmoj_nginx_network
      - default
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=anacnu.kr
      - PORT=${PORT}
      - FLASK_SERVER_URL=${FLASK_SERVER_URL}
  
networks:
  dmoj_nginx_network:
    external: true